# Hands-On Assignment 3

In this assignment, you will learn the basics of data cleaning and munging (manipulation).
Data is the heart and soul of a data scientist and machine learner.
Therefore, it is important for you to get comfortable taking data from its natural, messy state
to a state where it is ready for machine learning algorithms.

Since data is at the core of all we do, we learn to love data and treat it well.
However, not everyone is a data scientist, a computer scientist, or even a programmer.
Others that you work with may carefully collect very important data,
but handling and storing the data may not be their expertise.
So whenever working with data prepared by others,
we must always treat their data with care and remember that even data presented in suboptimal ways can be of the utmost importance.
Also remember that even as we learn better data handling practices,
there will still be those with data handling skill and methodologies that are leagues better than our own.
(It's database people, they are usually the best data people. (Written by Eriq, a database person.))

The objective of this assignment is for you to learn about:
 - Finding errors and inconsistencies in data.
 - Extracting key pieces of information from a data column.
 - Assigning types to data columns.
 - Understanding and finding outliers in your data.
 - Replacing missing pieces of data.
 - Encoding data.
 - Joining data.

## Data: CIA World Factbook - 2022

For this assignment, we will be using data from the [CIA World Factbook](https://www.cia.gov/the-world-factbook/).
This is a collection of real data about different countries and regions in the world compiled every year by the CIA.
Specifically, we will be using the world factbook data from [this repository](https://github.com/factbook/factbook.json/) from 2022.

The data can be found in your assignment repository in the `cia_world_factbook_2022.json` file.

Let's take a look at the data as we have done in previous assignments:

In [216]:
import json
import re
import pandas
import numpy
import math

# Our data comes in JSON, so first parse the JSON data.
with open('cia_world_factbook_2022.json', 'r') as file:
    data = json.load(file)

# Now load the JSON data into a Pandas dataframe.
world_data = pandas.DataFrame.from_dict(data, orient = 'index')

# Sort the data by country name so it looks nice.
world_data.sort_index(axis = 0, inplace = True)

# Move the country name out of the index and into an actual column.
world_data.insert(0, 'Country', world_data.index)
world_data.reset_index(drop = True, inplace = True)
print(len(world_data))
print(world_data.columns)

250
Index(['Country', 'Life expectancy', 'Population', 'Literacy',
       'Electricity access', 'Internet access', 'Improved Sanitation',
       'Improved Water', 'Export commodities', 'Labor Agriculture',
       'Labor Industry', 'Labor Services', 'Unemployment rate 2021',
       'Unemployment rate 2020', 'Unemployment rate 2019',
       'Unemployment rate 2016', 'Unemployment rate 2010',
       'Unemployment rate 2017', 'Labor Industry and Services',
       'Unemployment rate 1997', 'Unemployment rate 2000',
       'Unemployment rate 2008', 'Unemployment rate 2004',
       'Unemployment rate 2013', 'Unemployment rate 2011',
       'Unemployment rate 2012', 'Unemployment rate 2014',
       'Unemployment rate 1998', 'Unemployment rate 2015',
       'Unemployment rate 2002', 'Unemployment rate 2018',
       'Unemployment rate April 2011', 'Unemployment rate 2006',
       'Unemployment rate 2005', 'Unemployment rate 2001'],
      dtype='object')

Let's also take a look at the column information:

In [217]:
world_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 35 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Country                       250 non-null    object
 1   Life expectancy               233 non-null    object
 2   Population                    250 non-null    object
 3   Literacy                      229 non-null    object
 4   Electricity access            219 non-null    object
 5   Internet access               227 non-null    object
 6   Improved Sanitation           230 non-null    object
 7   Improved Water                247 non-null    object
 8   Export commodities            232 non-null    object
 9   Labor Agriculture             212 non-null    object
 10  Labor Industry                207 non-null    object
 11  Labor Services                198 non-null    object
 12  Unemployment rate 2021        187 non-null    object
 13  Unemployment rate 2020        187 non-null    object
 14  Unemployment rate 2019        188 non-null    object
 15  Unemployment rate 2016        10 non-null     object
 16  Unemployment rate 2010        3 non-null      object
 17  Unemployment rate 2017        8 non-null      object
 18  Labor Industry and Services   13 non-null     object
 19  Unemployment rate 1997        2 non-null      object
 20  Unemployment rate 2000        3 non-null      object
 21  Unemployment rate 2008        4 non-null      object
 22  Unemployment rate 2004        2 non-null      object
 23  Unemployment rate 2013        2 non-null      object
 24  Unemployment rate 2011        3 non-null      object
 25  Unemployment rate 2012        3 non-null      object
 26  Unemployment rate 2014        3 non-null      object
 27  Unemployment rate 1998        1 non-null      object
 28  Unemployment rate 2015        7 non-null      object
 29  Unemployment rate 2002        1 non-null      object
 30  Unemployment rate 2018        1 non-null      object
 31  Unemployment rate April 2011  1 non-null      object
 32  Unemployment rate 2006        1 non-null      object
 33  Unemployment rate 2005        4 non-null      object
 34  Unemployment rate 2001        1 non-null      object
dtypes: object(35)
memory usage: 68.5+ KB

Now the numerical values:

In [218]:
world_data.describe()

,Country,Life expectancy,Population,Literacy,Electricity access,Internet access,Improved Sanitation,Improved Water,Export commodities,Labor Agriculture,...,Unemployment rate 2012,Unemployment rate 2014,Unemployment rate 1998,Unemployment rate 2015,Unemployment rate 2002,Unemployment rate 2018,Unemployment rate April 2011,Unemployment rate 2006,Unemployment rate 2005,Unemployment rate 2001
count,250,233,250,229,219,227,230,247,232,212,...,3,3,1,7,1,1,1,1,4,1
unique,250,207,243,118,68,132,122,102,232,154,...,3,3,1,7,1,1,1,1,4,1
top,Afghanistan,NA,(July 2021 est.) no indigenous inhabitants,NA,100% (2020),78% (2020 est.),total: 100% of population,total: 100% of population,"gold, grapes, opium, fruits and nuts, insect r...",NA,...,2% (2012),11% (2014 est.),6% (1998 est.),4.1% (2015 est.),8% (2002),3.69% (2018 est.),2% (April 2011 est.),36% (2006 est.),29.8% (2005),12% (2001)
freq,1,7,4,66,125,10,54,54,1,7,...,1,1,1,1,1,1,1,1,1,1

Note that when we tried to get information about the numerical columns like in a previous assignment,
we didn't get nearly as much information as we did before.
If we look back to `world_data.info()`,
we can see this is because Pandas doesn't actually know which of our columns are numbers
(the dtype ("data type") for each column is just `object`).
If we look at some of the values (like "38,346,720 (2022 est.)"),
we can see why Pandas would be confused about how to treat that data.
Pandas will always try and choose a data type that can be applied to every value in the column.
So if a column has a million ints and one float, then the column type will be float
(since all ints are floats, but not all floats are ints).

Let's see if we can cleanup this data!

## Part 1: Exploring Columns

The first thing to do with a new dataset is explore the columns.
 - What data is each column suppose to contain?
 - What data type should be used to represent each column?
 - Which columns may be useful?

Not all columns in each dataset are going to be useful.
We can start our work by eliminating columns that have a low chance of being needed.

<h3 style="color: darkorange; font-size: x-large";>★ Task 1.A</h3>

Complete the following function that takes in a frame and drops the columns in the frame that have greater than `sparsity_threshold` percent of values empty.
Assume any value that [Pandas.isna](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.isna.html) returns true for is "empty".
Return the passed-in frame.

In [219]:
def drop_sparse_columns(frame, sparsity_threshold):
    num_rows = len(frame)
    to_drop = []
    for col in frame.columns:
        num_empty = 0
        for row in frame.index:
            if pandas.isna(frame[col][row]):
                num_empty += 1
        if ((float(num_empty) / float(num_rows)) >= sparsity_threshold):
            to_drop.append(col)
    for items in to_drop:
        frame.pop(items)
    return frame
        

drop_sparse_columns(world_data, 0.50)
world_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Country                 250 non-null    object
 1   Life expectancy         233 non-null    object
 2   Population              250 non-null    object
 3   Literacy                229 non-null    object
 4   Electricity access      219 non-null    object
 5   Internet access         227 non-null    object
 6   Improved Sanitation     230 non-null    object
 7   Improved Water          247 non-null    object
 8   Export commodities      232 non-null    object
 9   Labor Agriculture       212 non-null    object
 10  Labor Industry          207 non-null    object
 11  Labor Services          198 non-null    object
 12  Unemployment rate 2021  187 non-null    object
 13  Unemployment rate 2020  187 non-null    object
 14  Unemployment rate 2019  188 non-null    object
dtypes: object(15)
memory usage: 29.4+ KB

Now that we have fewer columns to worry about,
we can take a closer look at our data.

It looks like this data was originally meant for people and not machines.
There are several things that make it easier for people to read, but harder for us machine learning folks:
 - Commas in numeric values: '38,346,720' instead of '38346720'.
 - Units after numbers: '53.65 years', '37.3%'.
 - Notes about the data interweaved with the data itself: '37.6% (2017 est.)' instead of just '37.6%' (or better: '0.376').

Externally displaying data with these traits can really help analysts and non-data scientists,
but can really get in the way of our data analysis work.
When possible, we want to store the data cleanly and translate it to a more human readable form (often called a *report*) for readers, analysts, managers, etc..
This also makes it easier to transform our data in different ways
(like using a dot instead of a comma as a decimal separator in some countries: '1,000' vs '1.000').

In our data, it looks like many columns just contain a single main number with some potential context information around it:

In [220]:
world_data['Population'][0]

'38,346,720 (2022 est.)'

There are also more complex cases that contain multiple relevant numbers:

In [221]:
world_data['Population'][1]

'(2020) approximately 18,195 on the Sovereign Base Areas of Akrotiri and Dhekelia including 11,000 Cypriots and 7,195 Service and UK-based contract personnel and dependents'

We will want to clean up these cells so that they contain just the core piece of information and not all that extra information.

<h3 style="color: darkorange; font-size: x-large";>★ Task 1.B</h3>

Complete the following function that takes in a frame and a list of columns to ignore.
For all columns that are not ignored,
extract a number from the cell's text and replace the cell's contents with that correctly typed number (either a `float` or `int`).
The number should be converted to an `int` if the text does not have a decimal point (and is not a percentage).
If the cell contains no number, replace it with a `numpy.nan`.
Convert percentages to normalized floats, e.g., `str('37.6% (2017 est.)')` turns into `float(0.376)`.
Return the passed-in frame.

For cells with ambiguous data/numbers,
it is your job to do your best to honor what that data's author likely intended.

**Warning:
This is a hard task with no exact answer (as with most tasks in machine learning).
Look through the data to find as many edge cases as you can, turn those into test cases, and see how many you can solve.
Start with a simple solution and work up from there.**

In [222]:
def extract_numbers(frame, ignore_columns = []):

    # Check for the format of the numbers and the consistency of the string.
    for col in frame.columns:
        if col in ignore_columns:
            print(f"ignore {col}")
            continue
        for row in frame.index:
            entry = frame[col][row]
            # frame[col][row] = 9
            if isinstance(entry, str):
                v = re.search(r"(^NaN$)|(^NA$)|(^total: NA$)", entry)
                if v is not None or entry == '':
                    frame[col][row] = numpy.nan
                    continue
                x = re.search(r"[0-9]+\.[0-9]+(?!\))", entry)
                if x is not None:
                    y = re.search(r"[0-9]+\.[0-9 ]+[%]{1}(?!\))", entry)
                    if y is not None:
                        frame[col][row] = float(x.group()) / 100
                    else:
                        frame[col][row] = float(x.group())
                    continue
                z = re.search(r"[0-9,]*[0-9]+(?!\))", entry)
                if z is not None:
                    int_entry = z.group()
                    int_entry = int_entry.replace(",", "")
                    x_percent = re.search(r"[0-9,]*[0-9 ]+[%]{1}(?!\))", entry)
                    if x_percent is not None:
                        frame[col][row] = float(int_entry) / 100
                    else:
                        frame[col][row] = int(int_entry)
                    
                    continue
                frame[col][row] = numpy.nan
            
    return frame

print("Cleaning up the numeric values:")
extract_numbers(world_data, ['Country', 'Export commodities'])
print(len(world_data))

Cleaning up the numeric values:
ignore Country
ignore Export commodities
250

As a consequence of what we just did, we also standardized all the NaN values in those columns.
Before we could see empty values represented in several different ways:
 - 'NaN'
 - 'NA'
 - 'total: NA'
 - '' (empty)

Now, since any cell that didn't contain a number was replaced with `numpy.nan`,
all numeric cells with missing/empty values are consistent.

Now that we have cleaned up our numeric columns,
let's officially tell Pandas the data types for our columns.
Because even though most of our columns now only contains numbers (and `numpy.nan`),
Pandas still needs to be told what data type each column uses.

In [223]:
world_data.describe()

,Country,Life expectancy,Population,Literacy,Electricity access,Internet access,Improved Sanitation,Improved Water,Export commodities,Labor Agriculture,Labor Industry,Labor Services,Unemployment rate 2021,Unemployment rate 2020,Unemployment rate 2019
count,250,226.00,243,163.000,219.0,227.00,214.0,224.0,232,204.0,199.0,190.00,187.0000,187.0000,188.0000
unique,250,206.00,240,117.000,63.0,92.00,121.0,100.0,232,149.0,133.0,162.00,175.0000,177.0000,172.0000
top,Afghanistan,76.13,2021,0.998,1.0,0.78,1.0,1.0,"gold, grapes, opium, fruits and nuts, insect r...",0.8,0.2,0.75,0.0217,0.2589,0.0445
freq,1,3.00,4,9.000,130.0,10.00,54.0,54.0,1,5.0,9.0,3.00,2.0000,2.0000,4.0000

<h3 style="color: darkorange; font-size: x-large";>★ Task 1.C</h3>

Complete the following function that takes in a frame and assigns the closest matching type to each column.
You can choose from the following three types: `int`, `float`, and `str`.
(Note that columns containing only integers should have the `int` type, not the `float` type.)
Ignore any `numpy.nan` values when making decisions.
Return the passed-in frame.

In [224]:
def guess_types(frame):
    
    for col in frame.columns:
        contains_str = 0
        types = {"flt": 0, "int": 0}
        for item in frame.index:
            subject = frame[col][item]
            
            if isinstance(subject, int):
                if numpy.isnan(subject):
                    frame.at[item, col] = -9999
                    continue
                types["int"] += 1
            elif isinstance(subject, float):
                if numpy.isnan(subject):
                    frame.at[item, col] = -9999
                    continue
                types["flt"] += 1
            elif isinstance(subject, str):
                contains_str = 1
                break
        if contains_str:
            frame[col].astype('str')
            continue

        max = "None"
        max_int = 0
        for t in types.keys():
            if types[t] > max_int:
                max = t
                max_int = types[t]
        if max_int != 0:
            if max == "int":
                frame[col] = frame[col].astype('int64')
                # print(f"casting {col} to int\n\n")
            if max == "flt":
                frame[col] = frame[col].astype(float)
                # print(f"casting {col} to float\n\n")
        # print(f"finished looking at {col}")
    return frame
print("Data description after types are assigned:")
guess_types(world_data)
world_data.describe()

Data description after types are assigned:

,Life expectancy,Population,Literacy,Electricity access,Internet access,Improved Sanitation,Improved Water,Labor Agriculture,Labor Industry,Labor Services,Unemployment rate 2021,Unemployment rate 2020,Unemployment rate 2019
count,250.000000,2.500000e+02,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000
mean,-892.479760,3.156233e+07,-3479.092004,-1239.118228,-919.344796,-1439.120276,-1039.056776,-1839.514644,-2039.642468,-2399.253352,-2519.683636,-2519.683353,-2479.696195
std,2973.549697,1.308484e+08,4772.848206,3302.382438,2895.947462,3517.890827,3058.709652,3882.370279,4037.447557,4279.256198,4349.924368,4349.924532,4326.780692
min,-9999.000000,-9.999000e+03,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000
25%,67.532500,1.162218e+05,-9999.000000,0.515000,0.293500,0.572000,0.842500,0.012000,0.050000,0.060000,-7499.249350,-7499.249475,0.001125
50%,75.220000,4.263310e+06,0.768500,1.000000,0.640000,0.935500,0.975000,0.095500,0.162000,0.495500,0.050500,0.049600,0.042000
75%,78.920000,1.958118e+07,0.966750,1.000000,0.847500,0.998000,0.999000,0.387750,0.223500,0.698750,0.091225,0.091450,0.078025
max,89.520000,1.410540e+09,1.000000,1.000000,1.000000,1.000000,1.000000,20.060000,0.630000,20.060000,0.335600,0.292200,0.284700

Now we can see more complete statistics for our numerical columns.
Our data is so much cleaner than when we started,
but it still has some issues lurking in it and is not ready for our machine learning algorithms.

## Part 2: Data Cleaning and Smoothing

Now that our data is cleaner, we can look closer at our numbers.
It is always important to take time to go over your data.
To help understand our data, we will use both aggregate statistics and manual inspection.

### Data Outliers

Now, you may notice some inconsistencies (depending on how well you did in previous parts)
in your data statistics (`describe()`).
For example, you may notice a value for a percentage column above 1.0 or a population in the single digits.
Looking at these aggregate statistics can help us recognize that there are issues in our data.
However, we still need to isolate the specific entries with issues and fix them.

To start, we want to look for [outliers](https://en.wikipedia.org/wiki/Outlier) in our data.
An outlier is just a point that lies "outside" the expected range for our data.
The exact definition for what is considered "outside" our expected range depends on the dataset and situation.

<h3 style="color: darkorange; font-size: x-large";>★ Task 2.A</h3>

Complete the function below which takes in a frame, a number of standard deviations, and the name of a label column.
This function will search all numeric columns for outliers.
An outlier will be any value that is more that the specified number of standard deviations away from the column's mean.
Any NaNs should be ignored.

The return value should be a dict where the keys are the names of columns that contain an outlier
and the value is a list of tuples with the value of the label column for that row and the outlier value.
Columns without outliers (and non-numeric columns) should be omitted from the returned result.

For example, a valid return from `find_outliers(world_data, 4.0, 'Country')` could be:
```
{
    'Population': [
        ('China', 1410539758.0),
        ('India', 1389637446.0)
    ]
}
```

Use this function as a chance to catch bugs you may have in your number parsing function.

In [225]:
def std_of_col(frame, mean, col):
    diff_mean_item_sq = 0
    is_a_num = 0
    for item in frame.index:
        subject = frame[col][item]
        if int(subject) != -9999:
            diff = subject - mean
            diff = diff * diff
            diff_mean_item_sq += diff
            is_a_num += 1
    diff_mean_item_sq /= is_a_num
    squared_res = math.sqrt(diff_mean_item_sq)
    return squared_res

def mean_of_col(frame, col):
    mean = 0
    is_a_num = 0
    for item in frame.index:
        subject = frame[col][item]
        if int(subject) != -9999:
            mean += subject
            is_a_num += 1
    mean = mean / is_a_num
    return mean

def find_outliers(frame, deviations, label_column_name):
    # loop through all the columns.
    # if the column is numeric, find mean and std.
    # {'Population':[(country, number),(country, number)]}
    outliers = {}
    for col in frame.columns:
        std = 0
        mean = 0
        if frame[col].dtype != object:
            mean = mean_of_col(frame, col)
            std = std_of_col(frame, mean, col)
            for item in frame.index:
                if (abs(mean - frame[col][item]) > (deviations * std)) and \
                        frame[col][item] != -9999:
                    if (outliers.get(col) is None):
                        outliers[col] = []
                        outliers[col].append((frame[label_column_name][item], frame[col][item]))
                    else:
                        outliers[col].append((frame[label_column_name][item], frame[col][item]))
    print(len(outliers))
    return outliers

print("Outliers found in our data:")
find_outliers(world_data, 4.0, 'Country')

Outliers found in our data:
6

{'Population': [('China', 1410539758), ('India', 1389637446)],
 'Improved Water': [('Papua New Guinea', 0.475)],
 'Labor Agriculture': [('Tonga', 20.06)],
 'Labor Industry': [('Brunei', 0.628), ('North Korea', 0.63)],
 'Labor Services': [('Tonga', 20.06)],
 'Unemployment rate 2021': [('South Africa', 0.3356)]}

Once we have found outliers in our data, we have the hard decision of what to do with the outliers:
 - Are the outliers errors in the original data that we should discuss with the original data authors?
 - Are they a symptom of incorrect data parsing earlier in our pipeline?
 - Should they be replaced with a more typical value?
 - Should they be removed entirely?
 - Are they real and should just be kept in the data without modification.

In our case, we will keep our outliers intact.
However, use this as an opportunity to look for bugs in you number parsing code from Part 1.
Incorrectly parsed numbers can easily show up as outliers.

### Data Imputation

Besides outliers, another form of anomalous data we may see are *missing values*.
Missing values may be represented in many different ways depending on the dataset:
numpy.nan, -1, null, None, "MISSING", etc.

Sometimes what to do with missing data is obvious given the dataset.
For example, if a new country was founded in 2022 then the value in its "Unemployment rate 2019" should be missing.
Neither a 0.0 nor 1.0 would make sense, the value just does not exist.

However in more complex situations, deciding what to do with missing data can be very difficult.
One potential way to deal with missing data is through [data imputation](https://en.wikipedia.org/wiki/Imputation_(statistics)).
"Imputing" data is when we replace missing values with some derived value.
We are essentially "filling in the gaps" in our data with values that make sense.
There are many methods of choosing which values to impute, some of which are:
 - Using the **mean** value of the column (using non-empty values).
 - Using other values to create a machine learning model (often a regressor) to **predict** what the value should be.
 - Making a **random** guess (which can sometimes work better than you may expect).
 - Using knowledge of the domain to build a probabilistic model and then using that model to make a **educated random** guess.

There is no fixed rule or theorem that will tell you what the best data imputation method is for each dataset or column.
It will usually come down to the expertise of a data scientists (that's you!)
to bridge the gap between the domain data and statistics and figure our the best way to impute missing data (or whether to leave it be).
Always be careful when imputing values,
since it may bias your data.

In our data, the most sparsely populated columns (and candidates for imputation)
are "Literacy" and the three "Unemployment" columns.

The "Literacy" column could be a very interesting column to impute,
because there are many [studies on different predictors of literacy in adults](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0243763).
We may be able to use the other columns in our dataset (like "Electricity access", "Internet access", "Improved Sanitation", "Improved Water")
to predict literacy rate.
Unfortunately, building regressors is outside the scope of this assignment.

Still, the "Unemployment" columns also provides an interesting data imputation opportunity for us.
There are three columns that represent employment for three years ("Unemployment rate 2021", "Unemployment rate 2020", "Unemployment rate 2019"),
and each country may have values for any number of those columns.
To smooth out the data and impute missing values,
we can combine these columns into one ("Recent Unemployment") and take the **mean** of all present values.

<h3 style="color: darkorange; font-size: x-large";>★ Task 2.B</h3>

Complete the function below that takes a frame, a list of column names, and a new column name.
Modify the frame to merge the provided columns into a single column with the provided name.
To merge columns, take the mean of any present values.
If no values are present, use `numpy.nan`.
Return the passed-in frame.

In [226]:
def merge_columns(frame, merge_column_names, new_column_name):
    frame[new_column_name] = numpy.nan
    row_iter = 0
    num_rows = len(frame)
    print(num_rows)
    while (row_iter < num_rows):
        sum_col = 0
        num_vals = 0
        for col in merge_column_names:
            if frame[col][row_iter] != -9999:
                sum_col += frame[col][row_iter]
                num_vals += 1
        if (num_vals > 0):
            frame.at[row_iter, new_column_name] = sum_col / num_vals
        else:
            frame.at[row_iter, new_column_name] = numpy.nan
        row_iter += 1
    for to_pop in merge_column_names:
        frame.pop(to_pop)

    return frame
                
print("Data with merged unemployment data:")
columns = ['Unemployment rate 2019', 'Unemployment rate 2020', 'Unemployment rate 2021']
merge_columns(world_data, columns, 'Recent Unemployment')

Data with merged unemployment data:
250

,Country,Life expectancy,Population,Literacy,Electricity access,Internet access,Improved Sanitation,Improved Water,Export commodities,Labor Agriculture,Labor Industry,Labor Services,Recent Unemployment
0,Afghanistan,53.65,38346720,0.373,0.990,0.18,0.614,0.765,"gold, grapes, opium, fruits and nuts, insect r...",0.443,0.181,0.376,0.120700
1,Akrotiri,-9999.00,202,-9999.000,-9999.000,-9999.00,-9999.000,-9999.000,NaN,-9999.000,-9999.000,-9999.000,NaN
2,Albania,79.47,3095344,0.981,1.000,0.72,0.999,0.970,"leather footwear and parts, crude petroleum, i...",0.414,0.183,0.403,0.122067
3,Algeria,78.03,44178884,0.814,0.994,0.63,0.965,0.994,"crude petroleum, natural gas, refined petroleu...",0.108,0.309,0.584,0.119200
4,American Samoa,75.32,45443,-9999.000,-9999.000,0.31,0.990,0.998,canned tuna,-9999.000,0.155,0.464,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,Western Sahara,64.50,652271,-9999.000,-9999.000,-9999.00,-9999.000,-9999.000,phosphates 62% (2012 est.),0.500,0.500,-9999.000,NaN
246,Yemen,67.51,30984689,0.701,0.470,0.27,0.591,0.996,"crude petroleum, gold, fish, industrial chemic...",-9999.000,-9999.000,-9999.000,0.133400
247,Zambia,66.26,19642123,0.867,0.370,0.20,0.517,0.716,"copper, gold, gemstones, sulfuric acid, raw su...",0.548,0.099,0.353,0.128000
248,Zimbabwe,63.32,15121004,0.865,0.530,0.29,0.642,0.769,"gold, tobacco, iron alloys, nickel, diamonds, ...",0.675,0.073,0.252,0.051167
249,none,74.44,101009,-9999.000,0.820,0.35,0.883,0.786,"fish and fish products, coral/shells, scrap me...",0.009,0.052,0.939,NaN

## Part 3: Encoding Data

Let's finally deal with that pesky "Export commodities" column!
It's not a number, but represents a list of items.
It is common to deal with data that is not numeric (arbitrary strings, strings representing single items, strings representing list/sets of items, etc).
To deal with these non-numeric columns, we need to encode them.
That is, we need to convert them from a non-numeric form to a numeric one.

In computer science, there are many encodings and encoding methods.
An encoding that you are probably already familiar with is [ASCII](https://en.wikipedia.org/wiki/ASCII),
which is a way to represent Latin letters as numbers.
Encodings are just agreed upon ways to represent non-numeric values as numbers.

In machine learning and data science, probably the most popular encoding method is [the One-Hot encoding](https://en.wikipedia.org/wiki/One-hot).
In One-Hot encoding, we take all the possible values an item can take and assign each possible value an index.
Presence of that value results in a 1, which absence results in a 0.
Essentially, we are turning a list of items into a series of binary columns which ask "Do you have this value?".

For example, consider the following tables.
In the first one, a student's major is kept as a string (or a list of strings).
To encode it, a column is created for each possible major and a 1 is present if that student has that major
(otherwise a 0 is used).

<center><img src="one-hot.png"/></center>

<h3 style="color: darkorange; font-size: x-large";>★ Task 3.A</h3>

Complete the function below that takes in a frame and a column name.
The function should modify the frame to add multiple columns represented a one-hot encoding of the specified column.
Assume that the given column contains a comma-separated list of values.
Each value should be made lowercase and have additional whitespace removed from the beginning and end.
The new column names should be named: "`<old column name>: <value>`.
(Like in the students example above.)
Return **a new frame** with the columns of the passed-in frame (minus the specified column) and all the new one-hot columns.

Note that the above semantics will not work perfectly for our world data,
but it will provide a good starting point.

In [227]:
def one_hot(frame, column_name):
    nframe = frame.copy(deep = True)
    num_rows = len(frame)
    iter = 0
    arb_column_name = column_name
    if column_name == "''":
        arb_column_name = "empty_value"
    while (iter < num_rows):
        subject = nframe[column_name][iter]
        if isinstance(subject, str):
            list_data = subject.split(",")
            for list_item in list_data:
                list_item_formatted = list_item.lower()
                list_item_formatted = re.sub("^[ ]*", "", list_item_formatted)
                list_item_formatted = re.sub("[ ]*$", "", list_item_formatted)
                new_cat = arb_column_name + ": " + list_item_formatted
                if new_cat not in nframe.columns:
                    nframe[new_cat] = 0
                nframe.loc[iter, new_cat] = 1
        iter += 1
    nframe.drop(arb_column_name, axis = 1)
    return nframe

In [228]:
# Before calling your function, we are going to clean up the data a little bit.
# Remember to take you time and look at regexs one piece at a time.
world_data['Export commodities'].replace(r'\s*\(\d{4}(?:\s*est\.)?\)\s*', '',
                                         regex = True, inplace = True)
world_data['Export commodities'].replace(r'\s*\(\d{2}%\)\s*', '',
                                         regex = True, inplace = True)
world_data['Export commodities'].replace(r'\s*\d{2}%\s*', '',
                                         regex = True, inplace = True)
world_data
print("One-Hot encoded exports:")
world_data = one_hot(world_data, 'Export commodities')
world_data

One-Hot encoded exports:

/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0
/var/folders/23/bqw9bhvx7ql6wndx74_rv7nw0000gn/T/ipykernel_29290/1720168728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  nframe[new_cat] = 0

,Country,Life expectancy,Population,Literacy,Electricity access,Internet access,Improved Sanitation,Improved Water,Export commodities,Labor Agriculture,...,Export commodities: perfume plants,Export commodities: polyacetals,Export commodities: stone,Export commodities: olives,Export commodities: fruit,Export commodities: limestone,Export commodities: phosphates,Export commodities: industrial chemical liquids,Export commodities: sulfuric acid,Export commodities: coral/shells
0,Afghanistan,53.65,38346720,0.373,0.990,0.18,0.614,0.765,"gold, grapes, opium, fruits and nuts, insect r...",0.443,...,0,0,0,0,0,0,0,0,0,0
1,Akrotiri,-9999.00,202,-9999.000,-9999.000,-9999.00,-9999.000,-9999.000,NaN,-9999.000,...,0,0,0,0,0,0,0,0,0,0
2,Albania,79.47,3095344,0.981,1.000,0.72,0.999,0.970,"leather footwear and parts, crude petroleum, i...",0.414,...,0,0,0,0,0,0,0,0,0,0
3,Algeria,78.03,44178884,0.814,0.994,0.63,0.965,0.994,"crude petroleum, natural gas, refined petroleu...",0.108,...,0,0,0,0,0,0,0,0,0,0
4,American Samoa,75.32,45443,-9999.000,-9999.000,0.31,0.990,0.998,canned tuna,-9999.000,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,Western Sahara,64.50,652271,-9999.000,-9999.000,-9999.00,-9999.000,-9999.000,phosphates,0.500,...,0,0,0,0,0,0,1,0,0,0
246,Yemen,67.51,30984689,0.701,0.470,0.27,0.591,0.996,"crude petroleum, gold, fish, industrial chemic...",-9999.000,...,0,0,0,0,0,0,0,1,0,0
247,Zambia,66.26,19642123,0.867,0.370,0.20,0.517,0.716,"copper, gold, gemstones, sulfuric acid, raw su...",0.548,...,0,0,0,0,0,0,0,0,1,0
248,Zimbabwe,63.32,15121004,0.865,0.530,0.29,0.642,0.769,"gold, tobacco, iron alloys, nickel, diamonds, ...",0.675,...,0,0,0,0,0,0,0,0,0,0
249,none,74.44,101009,-9999.000,0.820,0.35,0.883,0.786,"fish and fish products, coral/shells, scrap me...",0.009,...,0,0,0,0,0,0,0,0,0,1

## Part 4: Joining Data

Data is not always from a single frame/table or source.
You will often need to merge and cross-reference data from other sources and in different frames.
When we talk about merging data from multiple frames or tables,
we usually use terminology that comes from databases and relational algebra.
So we say "table" to refer to the abstract concept of tabular data (data with rows and columns) like a Pandas.DataFrame.
Then, a [join](https://en.wikipedia.org/wiki/Join_(SQL)) is an operation that combines data from the columns of two different tables.
(Note that the same table can actually be used multiple times (called a "self-join"),
and joins can be chained together to include as many tables as desired.)

In this section, we will briefly show the main different types of joins.
The image below shows a graphical representation of the primary join types.
When discussing joins, we will refer to the table on the left side of the join operator as the LHS (left-hand side)
and the table on the right side of the join operator as the RHS (right-hand side).
In the diagram below, $ A $ is always the LHS and $ B $ is always the RHS.

Joins will typically specify some condition that must be meant for two rows to be merged,
referred to as a "join condition".
The most common join condition is equality for a set of columns.
When a collection of columns are checked for equality in a join,
we say we join "on" those columns.
For example, we may say that we join $ A $ and $ B $ on the "ID" column.

<center><img src="joins.png"/></center>

### Cross Join / Cartesian Product / Cross Product

Cross joins (also known an "Cartesian products" or "cross products")
are when every row in the LHS is paired with every row in the RHS.
Therefore, the resulting table will have $ |A| * |B| $ number of rows.

Cross joins can be though of as the basis for all other joins,
since all possible rows are enumerated.

### Inner Join

Inner joins take only the rows from the LHS and RHS where the join conditions are met.
We call an inner join where all shared columns (columns with the same name) between the LHS and RHS are checked for equality a *natural join*.

### Full Outer Join

Full outer joins (also known as "outer joins") ensure that every row from each table is represented.
First, rows where the join condition are met are included.
Then, rows from each table are included where the join condition are not met are included.
For these non-matching rows, any columns that come from the other table are filled in with null or empty values
(depending on the engine that performs the join).

### Left Outer Join

Left outer joins are like full outer joins,
except only the non-matching rows from the LHS are included.

### Right Outer Join

Left outer joins are like full outer joins,
except only the non-matching rows from the RHS are included.

Now that you are an expert in join types, let's get some new data to join!
To augment our data, we can get more information from the [World Health Organization](https://www.who.int/) (WHO).
To tie in with our previous HO, we can get some 2022 statistics for each country on their Covid-19 status.

In [229]:
with open('who_covid_data_2022.json', 'r') as file:
    data = json.load(file)

who_data = pandas.DataFrame.from_dict(data, orient = 'index')
who_data.sort_index(axis = 0, inplace = True)
who_data.head()

,Code,Cumulative_Confirmed,Per_100000_Confirmed,Last_7_Days_Confirmed,Last_7_Days_Confirmed_Per_100000,Confirmed,Cumulative_Deaths,Per_100000_Deaths,Last_7_Days_Deaths,Last_7_Days_Deaths_Per_100000,Deaths,Total_Vaccinations,Total_Vaccinations_Per_100,Total_One_Dose,Total_One_Dose_Per_100,Total_Fully_Vacc,Total_Fully_Vacc_Per_100,Total_Boosted,Total_Boosted_Per_100
Afghanistan,AF,207969,534.235,159,0.408,16,7855,20.178,3,0.008,0,12526397.0,32.178,11533150.0,29.627,10825004.0,27.808,NaN,NaN
Albania,AL,333072,11573.841,134,4.656,8,3596,124.957,0,0.000,0,3025728.0,105.100,1342243.0,47.163,1270016.0,44.625,377057.0,13.249
Algeria,DZ,271255,618.583,1,0.002,0,6881,15.692,0,0.000,0,15267442.0,34.817,7840131.0,17.879,6481186.0,14.780,575651.0,1.313
American Samoa,AS,8309,15053.354,0,0.000,0,34,61.598,0,0.000,0,111316.0,201.670,44885.0,81.318,41423.0,75.046,24160.0,43.770
Andorra,AD,47781,61840.419,0,0.000,0,159,205.785,0,0.000,0,154367.0,199.800,57901.0,76.009,53485.0,70.211,42981.0,56.423

To perform joins in Pandas, a useful method is [DataFrame.join()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.join.html).
Of course, Pandas always has multiple ways to do anything, but the `DataFrame.join()` method is a good start.

<h3 style="color: darkorange; font-size: x-large";>★ Task 4.A</h3>

Complete the function below that takes in two frames and a list of column names.
This function should return a new frame that contains the left outer join between these frames on the specified columns from the LHS.

*Hint: Make sure to read the documentation on DataFrame.join() if you are going to use it.*

In [230]:
def left_join(lhs_frame, rhs_frame, column_names):
    frame = lhs_frame.join(rhs_frame, column_names, "left")
    return frame

print("World data that includes Covid-19 stats:")
covid_world_data = left_join(world_data, who_data, ['Country'])
covid_world_data

World data that includes Covid-19 stats:

,Country,Life expectancy,Population,Literacy,Electricity access,Internet access,Improved Sanitation,Improved Water,Export commodities,Labor Agriculture,...,Last_7_Days_Deaths_Per_100000,Deaths,Total_Vaccinations,Total_Vaccinations_Per_100,Total_One_Dose,Total_One_Dose_Per_100,Total_Fully_Vacc,Total_Fully_Vacc_Per_100,Total_Boosted,Total_Boosted_Per_100
0,Afghanistan,53.65,38346720,0.373,0.990,0.18,0.614,0.765,"gold, grapes, opium, fruits and nuts, insect r...",0.443,...,0.008,0.0,12526397.0,32.178,11533150.0,29.627,10825004.0,27.808,NaN,NaN
1,Akrotiri,-9999.00,202,-9999.000,-9999.000,-9999.00,-9999.000,-9999.000,NaN,-9999.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Albania,79.47,3095344,0.981,1.000,0.72,0.999,0.970,"leather footwear and parts, crude petroleum, i...",0.414,...,0.000,0.0,3025728.0,105.100,1342243.0,47.163,1270016.0,44.625,377057.0,13.249
3,Algeria,78.03,44178884,0.814,0.994,0.63,0.965,0.994,"crude petroleum, natural gas, refined petroleu...",0.108,...,0.000,0.0,15267442.0,34.817,7840131.0,17.879,6481186.0,14.780,575651.0,1.313
4,American Samoa,75.32,45443,-9999.000,-9999.000,0.31,0.990,0.998,canned tuna,-9999.000,...,0.000,0.0,111316.0,201.670,44885.0,81.318,41423.0,75.046,24160.0,43.770
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,Western Sahara,64.50,652271,-9999.000,-9999.000,-9999.00,-9999.000,-9999.000,phosphates,0.500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246,Yemen,67.51,30984689,0.701,0.470,0.27,0.591,0.996,"crude petroleum, gold, fish, industrial chemic...",-9999.000,...,0.000,0.0,1242982.0,4.167,1006274.0,3.374,761003.0,2.551,59307.0,0.199
247,Zambia,66.26,19642123,0.867,0.370,0.20,0.517,0.716,"copper, gold, gemstones, sulfuric acid, raw su...",0.548,...,0.000,0.0,13581376.0,73.876,10937674.0,59.496,8530651.0,46.403,1026839.0,5.586
248,Zimbabwe,63.32,15121004,0.865,0.530,0.29,0.642,0.769,"gold, tobacco, iron alloys, nickel, diamonds, ...",0.675,...,0.000,0.0,12694853.0,85.413,6558577.0,44.127,4927696.0,33.154,1208580.0,8.132
249,none,74.44,101009,-9999.000,0.820,0.35,0.883,0.786,"fish and fish products, coral/shells, scrap me...",0.009,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Now we can see our country data along with Covid-19 data for each country!

In [231]:
covid_world_data.describe()

,Life expectancy,Population,Literacy,Electricity access,Internet access,Improved Sanitation,Improved Water,Labor Agriculture,Labor Industry,Labor Services,...,Last_7_Days_Deaths_Per_100000,Deaths,Total_Vaccinations,Total_Vaccinations_Per_100,Total_One_Dose,Total_One_Dose_Per_100,Total_Fully_Vacc,Total_Fully_Vacc_Per_100,Total_Boosted,Total_Boosted_Per_100
count,250.000000,2.500000e+02,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,...,194.000000,194.000000,1.910000e+02,191.000000,1.920000e+02,192.000000,1.920000e+02,192.000000,1.760000e+02,176.000000
mean,-892.479760,3.156233e+07,-3479.092004,-1239.118228,-919.344796,-1439.120276,-1039.056776,-1839.514644,-2039.642468,-2399.253352,...,0.218227,3.479381,5.840495e+07,152.249194,2.428285e+07,62.836734,2.242500e+07,57.710062,1.186132e+07,32.114188
std,2973.549697,1.308484e+08,4772.848206,3302.382438,2895.947462,3517.890827,3058.709652,3882.370279,4037.447557,4279.256198,...,0.672357,31.150181,3.019056e+08,85.124399,1.219068e+08,26.471725,1.164194e+08,26.331122,6.412856e+07,26.028057
min,-9999.000000,-9.999000e+03,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,...,0.000000,0.000000,1.380000e+02,0.256000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000
25%,67.532500,1.162218e+05,-9999.000000,0.515000,0.293500,0.572000,0.842500,0.012000,0.050000,0.060000,...,0.000000,0.000000,5.054580e+05,80.356500,2.695368e+05,44.057000,2.203640e+05,38.151250,4.532600e+04,7.638000
50%,75.220000,4.263310e+06,0.768500,1.000000,0.640000,0.935500,0.975000,0.095500,0.162000,0.495500,...,0.000000,0.000000,4.523381e+06,161.900000,2.789580e+06,67.455000,2.504098e+06,63.219000,6.256960e+05,30.903500
75%,78.920000,1.958118e+07,0.966750,1.000000,0.847500,0.998000,0.999000,0.387750,0.223500,0.698750,...,0.055500,0.000000,2.010046e+07,215.910000,9.382555e+06,82.212750,8.168116e+06,78.394500,4.546497e+06,54.206000
max,89.520000,1.410540e+09,1.000000,1.000000,1.000000,1.000000,1.000000,20.060000,0.630000,20.060000,...,5.693000,415.000000,3.465114e+09,469.778000,1.307512e+09,163.185000,1.277357e+09,163.185000,8.048508e+08,145.944000

Note that we will likely have rows from our world data that did not match up with the WHO data.
To see these, we can just look for empty values in WHO columns (since a left join would put empty values there).

In [232]:
covid_world_data[covid_world_data['Total_Vaccinations'].isnull()]

,Country,Life expectancy,Population,Literacy,Electricity access,Internet access,Improved Sanitation,Improved Water,Export commodities,Labor Agriculture,...,Last_7_Days_Deaths_Per_100000,Deaths,Total_Vaccinations,Total_Vaccinations_Per_100,Total_One_Dose,Total_One_Dose_Per_100,Total_Fully_Vacc,Total_Fully_Vacc_Per_100,Total_Boosted,Total_Boosted_Per_100
1,Akrotiri,-9999.00,202,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,NaN,-9999.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Antarctica,-9999.00,54,-9999.000,-9999.000,1.000,-9999.000,-9999.000,NaN,-9999.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Ashmore and Cartier Islands,-9999.00,2021,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,NaN,-9999.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,"Baker Island, Howland Island, Jarvis Island, J...",-9999.00,-9999,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,NaN,-9999.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Bolivia,72.50,12054379,0.925,0.930,0.600,0.831,0.935,"natural gas, gold, zinc, soybean oil and soy p...",0.294,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Bouvet Island,-9999.00,-9999,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,NaN,-9999.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Brunei,78.38,478054,0.972,1.000,0.950,-9999.000,0.999,"natural gas, crude petroleum, refined petroleu...",0.042,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Burma,69.92,57526449,0.891,0.510,0.350,0.852,0.853,"natural gas, clothing products, rice, copper, ...",0.700,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,Christmas Island,-9999.00,2205,-9999.000,-9999.000,0.360,-9999.000,-9999.000,"calcium phosphates, fertilizers, valves, air p...",-9999.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Clipperton Island,-9999.00,-9999,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,NaN,-9999.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Cocos (Keeling) Islands,-9999.00,596,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,"computers, packaged medicines, precious metal ...",-9999.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,Congo (Brazzaville),62.10,5546307,0.803,0.720,0.090,0.547,0.842,"crude petroleum, copper, lumber, ships, refine...",0.354,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,Coral Sea Islands,-9999.00,2021,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,NaN,-9999.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,Cote d'Ivoire,62.26,28713423,0.899,0.760,0.360,0.571,0.798,"cocoa beans, gold, rubber, refined petroleum, ...",0.680,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,Curacao,79.42,152379,-9999.000,1.000,0.680,1.000,1.000,"gold, precious metal scraps, petroleum coke, f...",0.012,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,DRC,61.83,108407721,0.770,0.090,0.140,0.355,0.594,"copper, cobalt, crude petroleum, diamonds",-9999.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,Dhekelia,-9999.00,15500,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,NaN,-9999.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,Eritrea,66.85,6209262,0.766,0.470,0.010,0.157,0.578,"gold and other minerals, livestock, sorghum, t...",0.800,...,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN
74,Falkland Islands (Islas Malvinas),77.90,3198,-9999.000,-9999.000,0.990,1.000,0.953,"mollusks, fish, wool, sheep/goat meats, engine...",0.410,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,French Southern and Antarctic Lands,-9999.00,-9999,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,NaN,-9999.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,Gaza Strip,75.40,1997328,0.975,1.000,0.750,0.996,0.989,"strawberries, carnations, vegetables, fish (sm...",0.052,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,Heard Island and McDonald Islands,-9999.00,-9999,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,NaN,-9999.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,Holy See (Vatican City),-9999.00,1000,-9999.000,1.000,-9999.000,-9999.000,1.000,NaN,-9999.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,Hong Kong,83.61,7276588,-9999.000,1.000,0.920,0.964,1.000,"gold, broadcasting equipment, integrated circu...",0.038,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,Iran,75.25,86758304,0.855,1.000,0.840,1.000,0.994,"crude petroleum, polymers, industrial alcohols...",0.163,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,Jan Mayen,-9999.00,-9999,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,NaN,-9999.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,Kosovo,71.12,1952701,-9999.000,1.000,0.840,-9999.000,-9999.000,"mining and processed metal products, scrap met...",0.044,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,Laos,68.15,7749595,0.847,0.950,0.340,0.822,0.888,"electricity, copper, rubber, gold, flavored water",0.731,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,Macau,84.98,635293,0.965,1.000,0.880,-9999.000,1.000,"broadcasting equipment, jewelry, watches, trun...",0.025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
142,Moldova,72.44,3287326,0.994,1.000,0.763,0.899,0.921,"insulated wiring, sunflower seeds, wine, corn,...",0.323,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151,Navassa Island,-9999.00,-9999,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,NaN,-9999.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160,Norfolk Island,-9999.00,1748,-9999.000,-9999.000,0.350,-9999.000,-9999.000,"soybean meal, Norfolk Island pine seeds, Kenti...",0.060,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161,North Korea,71.77,25955138,1.000,0.260,-9999.000,0.853,0.945,"watch components, fake hair, iron alloys, inst...",0.370,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
163,Northern Mariana Islands,76.58,51475,-9999.000,1.000,0.310,0.979,1.000,"scrap iron, scrap copper, scrap aluminum, comp...",0.019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,Paracel Islands,-9999.00,1440,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,NaN,-9999.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,Russia,72.44,142021981,0.997,1.000,0.850,0.894,0.976,"crude petroleum, refined petroleum, natural ga...",0.094,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,Saint Barthelemy,80.58,7103,-9999.000,1.000,0.720,1.000,1.000,"beauty products, broadcasting equipment, sunfl...",-9999.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185,Saint Martin,80.58,32792,-9999.000,1.000,0.485,1.000,1.000,"gold, special use vessels, furniture, scrap al...",-9999.000,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
186,Saint Pierre and Miquelon,81.41,5257,-9999.000,-9999.000,0.795,1.000,0.914,"crustaceans, fish, medical instruments, electr...",0.180,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203,South Georgia and South Sandwich Islands,-9999.00,2021,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,NaN,-9999.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,South Korea,82.97,51844834,-9999.000,1.000,0.970,0.999,0.999,"integrated circuits, cars and vehicle parts, r...",0.048,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,Spratly Islands,-9999.00,2021,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,NaN,-9999.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
211,Svalbard (sometimes referred to as Spitsbergen...,-9999.00,2926,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,NaN,-9999.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
214,Syria,74.28,21563800,0.864,0.920,0.360,0.995,0.998,"olive oil, cumin seeds, pistachios, tomatoes, ...",0.170,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
215,Taiwan,81.16,23580712,0.985,-9999.000,0.890,-9999.000,-9999.000,"integrated circuits, office machinery/parts, c...",0.049,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
217,Tanzania,70.19,63852892,0.779,0.400,0.220,0.504,0.720,"gold, tobacco, cashews, sesame seeds, refined ...",0.669,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
219,The Bahamas,76.13,355608,-9999.000,1.000,0.870,0.982,0.989,"ships, refined petroleum, nitrogen compounds, ...",0.030,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
220,The Dominican,72.56,10694700,0.938,1.000,0.770,0.963,0.972,"gold, medical instruments, cigars, low-voltage...",0.144,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
221,The Gambia,67.60,2413403,0.508,0.490,0.370,0.600,0.895,"lumber, cashews, refined petroleum, fish oil, ...",0.750,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
228,Turkey,76.21,83047706,0.967,1.000,0.780,0.996,0.990,"cars and vehicle parts, refined petroleum, del...",0.184,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
234,United Kingdom,81.94,67791400,-9999.000,1.000,0.950,0.998,1.000,"cars, gas turbines, gold, crude petroleum, pac...",0.013,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
235,United States,80.59,337341954,-9999.000,1.000,0.910,0.997,0.999,"refined petroleum, crude petroleum, cars and v...",0.007,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
239,Venezuela,73.29,29789730,0.971,0.996,0.720,0.958,0.942,"crude petroleum, refined petroleum, industrial...",0.073,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
240,Vietnam,75.52,103808319,0.958,1.000,0.700,0.933,0.969,"broadcasting equipment, telephones, integrated...",0.403,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
241,Virgin Islands,80.27,105413,-9999.000,1.000,0.640,0.994,0.987,"refined petroleum, jewelry, recreational boats...",0.010,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
242,Wake Island,-9999.00,2018,-9999.000,1.000,-9999.000,-9999.000,-9999.000,NaN,-9999.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
244,West Bank,76.38,3000021,0.975,1.000,0.750,0.996,0.989,"stone, olives, fruit, vegetables, limestone",0.115,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
245,Western Sahara,64.50,652271,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,phosphates,0.500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
249,none,74.44,101009,-9999.000,0.820,0.350,0.883,0.786,"fish and fish products, coral/shells, scrap me...",0.009,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Looking at these results, we can understand why the WHO may not have data on some of them.
Some are not technically countries (like "Antarctica"),
some have ambiguous national status (like "Taiwan"),
and some are just using different but valid names (like "United States" vs "United States of America").

As a data scientist, think about ways that you could more efficiently join together these datasets.

Congratulations!
You now have a grasp on the basics of data cleaning and munging (the soul of a data scientist).